/**
 * Release notes shown on the main menu.
 *
 * Kept as data rather than markup so the menu can group and style it, and so there is one
 * obvious place to append to when something ships. Player-facing wording only — refactors,
 * build changes and internal invariants belong in CLAUDE.md, not here.
 */
export const RELEASE = Object.freeze({
  version: '0.7.6',
  stage: 'beta',

  changelog: [
    'Arcana has become Crafting: a new 3×3 pattern grid, five Artisan slots, recipe output, stack splitting, and drag-to-distribute materials across multiple cells.',
    'Added a large first set of Crafting recipes for stonework, textiles, lumber, leather, elemental essences, tools, alchemical reagents, Callings, and more.',
    'Added Tier I–V Pickaxes, Axes, Sickles, and Shortbows. Tools can roll from a pool of ten gathering affixes and slot directly beside compatible workers.',
    'Added Weaver, Woodworker, and Tanner processing specialists, Prospector miners, and Gemcutters for gem fusion.',
    'Higher-affix Miners, Prospectors, Lumberjacks, Foragers, and Hunters now make additional material rolls each cycle. Powerful cards can mass-gather common materials or make several attempts at rare finds.',
    'Mining and Gathering now use bottom progress bars, dedicated Tool/Buff spaces, and a staged loot display before rewards descend into the Collection Queue.',
    'Rebuilt the Wilderness and Foundry environments with richer animated scenery, lighting, atmosphere, water, foliage, lava, and performance-aware quality levels.',
    'The main menu now uses the illustrated mountain horizon as its splash artwork.',
    'Cards now use full-bleed artwork, rarity-colored borders, top-mounted affix stars, and clearer spacing around their lower details.',
    'Added card sockets and gem crafting. Cards may be summoned with up to three sockets, and can be inspected from the Hand to apply gems, Gemsetter’s Chisels, or Gem Extractors.',
    'Added five gem families across Dull, Cut, Brilliant, Exalted, and Royal tiers. Gem effects include focused card bonuses and Topaz item imprints.',
    'Gemcutters can fuse ten matching gems into the next tier using Gemdust and the matching elemental reagent.',
    'Added Elemental, Vocational, and Trait Callings. Craft an Empty Calling at a chosen tier, then specialize it to influence a Blank Slate pack.',
    'The Shop now rotates sixteen Goods and three featured packs every five minutes. Blank Slate remains permanently stocked, and repeated purchases raise an item’s price until the next rotation.',
    'High graphics now renders card packs as 3D models; Low and Medium retain lightweight pack art. Shop packs use rarity-colored backlighting instead of rectangular overlays.',
    'Rebuilt the Summoning altar with a stable pack stage, three square Attunement slots, larger reveals, centered queues, and distinct layouts for card and treasure rewards.',
    'Treasure rewards now reveal as square loot cards in the altar. Treasure packs can contain gems, ingots, rare woods, Gemsetter’s Chisels, and Gem Extractors.',
    'Opening a treasure pack now begins immediately when Open Pack is pressed, without requiring a second click on the chest.',
    'Inventory resources support both click-to-carry and natural drag-and-drop. Crafting materials can be spread evenly by dragging across grid cells.',
    'Forge and Processing inputs now show placed / required counts without covering their remove buttons, and outputs are collected independently per station row.',
    'Added optional station accelerants: Flux grants 10% smelting speed for five cycles, Arcane Flux grants 20% for fifteen cycles, and Tannin grants Tanners 15% for five cycles.',
    'Loot cards, layered queues, moving rewards, and held resources now preserve their artwork, borders, rounded corners, and correct paint order across station panels.',
    'Fixed 3D backgrounds remaining blurred after changing pages while High graphics was selected.',
    'Fixed Processing Collect taking unrelated bonus rewards and fixed Forge collection removing outputs from other rows.',
    'Fixed gathered resources and summoned loot being clipped by the edges of their station panels while moving to the queue.',
  ],

  known: [
    'Expedition, Lab, and Market remain unavailable while their gameplay loops are rebuilt.',
    'Pack Attunement is still in development. Elemental, Vocational, and Trait Callings are the first implemented Calling families.',
    'Drop rates, recipes, tool affixes, gem effects, and station speeds are still being balanced.',
    'Some sound effects may still play late or fail to play during very rapid interactions.',
    'Additional memory and graphics optimization is planned, including more detailed graphics controls.',
  ],

  planned: [
    'Additional Callings, Surges, Inscriptions, and pack-Attunement materials.',
    'More card classes, crafting recipes, tools, gems, and treasure rewards.',
    'Expanded card enchanting and targeted affix crafting.',
    'Merchant-driven shop upgrades, special deals, and more stock variance.',
    'Expedition system',
    'Multiplayer Market for card trading.',
  ],

  history: [
    {
      version: '0.7.5',
      stage: 'beta',
      changelog: [
        'New UI for Shop',
        'New UI for Inventory and Hand (previously "Pocket")',
        'Card scaling fixed',
        'Added a sound engine — you will hear sound effects and music now!',
        'Updated menu navigation UI',
        'Fixed runes not rising properly in navbar UI',
        'Expedition, Lab, and Market are no longer accessible as I work on these aspects of the gameplay loop.',
        'Added ambience SFX to Foundry and Wilderness',
        'Added 3D backdrops to Foundry and Wilderness',
        'New notification system shows where new loot has been acquired',
        'Players are now allowed to store a maximum of 20 card packs at once',
        'Created a new graphics setting (Low, Med, High).',
        'Added a volume mixer (change music, SFX, ambience, etc all separately).',
        'New UI for the Forge — everything you load is the same size and lined up, and the flow arrow now shows which materials are actually feeding the smelt.',
        'Fixed coal being destroyed when you refresh the game. Coal from older saves is recovered.',
        'Your Hand is now a fan of cards along the bottom of the screen instead of a drawer on the right. Hover a card to see it in full, and drag cards to the bottom of the screen to add them.',
        'The Bag now uses the full height of the screen.',
        'Fixed the audio mixer opening behind the menu bar.',
        'Cards are now the same size everywhere they are held — Foundry, Wilderness and your Hand.',
        'Fixed ingots not being slottable as a secondary smelting ingredient. You no longer have to load the ore first.',
        'Fixed the Foundry resizing itself when you collect.',
        'Your Hand now holds a maximum of 6 cards.',
        'Card placement sounds now play in full instead of being cut off early.',
        'The Bag tab is now a bookmark shape.',
        'The menu bar highlight no longer slides between tabs.',
        'One main menu now, with the mountains and the release notes on it. It no longer enters the game on its own — press Enter when you are ready.',
        'Hand cards sit higher and are much easier to read, and their remove button moved inside the card corner so it is easier to hit.',
        'The Hand is always visible now — no more show/hide button.',
        'Fixed loot in the Collection Queue rendering as tall cards until a second row appeared.',
        'Hovering a card in your Hand raises it half as far as before.',
        'Ores and ingots now always appear in their own Bag sections. Coal no longer jumps to "Gathered" after passing through the Forge, and gathered ingots are filed with smelted ones.',
        'Earning gold now sends a burst of gold up to your total in the corner. Bigger payouts throw a bigger stream, and the number climbs as the gold lands rather than before it.',
        'Treasure pack coins now burst where they sit instead of flying off to your Bag.',
        'New fonts throughout — one family for the wordmark, one for the menus, one for everything else.',
        'Loot notification diamonds now sit on the navbar line and pulse a much larger echo when new loot arrives.',
        'Cards can be dragged out of a work slot straight into your Hand, and pressing x releases them to your Collection instead.',
        'Fixed the card placement rings sometimes drawing over the front of the card.',
        'Wilderness Processing now uses the same layout as the Forge — full-size cards, equal slots, and a flow arrow that shows what is feeding the work.',
      ],
      known: [
        "Some SFX don't play properly or on time",
        'Memory and graphics optimization — will add more in-depth graphics options for players in the future.',
        "Arcana station still doesn't work as intended. Currently a work-in-progress.",
      ],
      planned: [
        'Crafting Station',
        'More card types',
        'Merchant to run the shop + more shop deals and variance.',
        'Additional item sockets for workers in Foundry and Wilderness to enhance card effects and focuses.',
        'Expedition system',
        'Multiplayer Market for card trading.',
      ],
    },
  ],
});
